### ISSUE TITLE
__invoke call with PHP 7.4 arrow function breaks test discovery

### ISSUE THREAD

**Issue by Deji69** [recca0120/phpunit-language-server#2]
**Minimal code to reproduce:**
```php
class TestTest {
	public function testCase() {
		// this is just to demonstrate code validity:
		$test = new class {
			public function __invoke($fn = null) { return $this; }
		};

		// fine:
		//$test(function () {})();

		// breaks test discovery:
		$test(fn() => false)();
	}

	public function testSecondCase()
	{}
}
```

Test discovery breaks when having the arrow function as an `__invoke` argument, and then following that call up with another `__invoke` call. No such breakage occurs if either the argument is not an arrow function (even closures work), or the call is not followed up by another `__invoke` call.

**Comment by Deji69** [comment]
The following message appears in the "PHPUnit Language Server" VSCode extension log:
```
(node:224) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'parenthesizedExpression' of undefined
    at read_expr_item (c:\Users\deji6\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:6:44458)
    at read_expr (c:\Users\deji6\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:6:41401)
    at read_statement (c:\Users\deji6\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:6:70110)
    at read_inner_statement (c:\Users\deji6\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:6:66614)
    at read_inner_statements (c:\Users\deji6\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:6:65359)
    at read_code_block (c:\Users\deji6\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:6:70293)
    at read_function (c:\Users\deji6\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:6:51304)
    at read_class_body (c:\Users\deji6\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:6:36668)
    at read_class (c:\Users\deji6\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:6:35853)
    at read_top_statement (c:\Users\deji6\.vscode\extensions\recca0120.vscode-phpunit-2.0.72\server\out\server.js:6:64640)
(node:224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 116)
```
